version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    networks:
      - microservices

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
    networks:
      - microservices

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - USER_SERVICE_URL=user-service:5001
      - PRODUCT_SERVICE_URL=product-service:5002
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api-gateway
    networks:
      - microservices

networks:
  microservices:
    driver: bridge 